language: python
sudo: required
group: deprecated-2017Q4
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
  matrix:
    - SANDBOX_MODE=
    - SANDBOX_MODE=True
cache:
  directories:
    - eggs
before_install:
  - sh bootstrap.sh
install:
  - bin/buildout -N
  - bin/buildout -N remotes:branch=$TRAVIS_BRANCH
  - bin/develop up --force
script:
  - bin/py.test ./openprocurement/tender/openua/tests/ --cov=openprocurement.tender.openua
#  - bin/pylint --errors-only --disable=no-member,not-an-iterable,bad-super-call,unsubscriptable-object,too-many-format-args openprocurement.tender.openua
after_success:
  - bin/coveralls
